#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

const DEFAULT_OUTPUT = './generated/mbpp.seed.sql'

const TOPIC_DEFINITIONS = [
  { id: 'regex_basic', displayName: 'Regular Expressions', difficultyBand: 'intermediate' },
  { id: 'json', displayName: 'JSON', difficultyBand: 'intermediate' },
  { id: 'csv', displayName: 'CSV', difficultyBand: 'intermediate' },
  { id: 'datetime', displayName: 'Datetime', difficultyBand: 'intermediate' },
  { id: 'collections_module', displayName: 'collections', difficultyBand: 'intermediate' },
  { id: 'itertools', displayName: 'itertools', difficultyBand: 'advanced' },
  { id: 'functools', displayName: 'functools', difficultyBand: 'advanced' },
  { id: 'typing_basic', displayName: 'Typing', difficultyBand: 'intermediate' },
  { id: 'classes_basic', displayName: 'Classes', difficultyBand: 'intermediate' },
  { id: 'dataclasses', displayName: 'Dataclasses', difficultyBand: 'intermediate' },
  { id: 'generators', displayName: 'Generators', difficultyBand: 'intermediate' },
  { id: 'exceptions', displayName: 'Exceptions', difficultyBand: 'intermediate' },
  { id: 'sets', displayName: 'Sets', difficultyBand: 'basic' },
  { id: 'dicts', displayName: 'Dicts', difficultyBand: 'basic' },
  { id: 'tuples', displayName: 'Tuples', difficultyBand: 'basic' },
  { id: 'lists', displayName: 'Lists', difficultyBand: 'basic' },
  { id: 'comprehensions', displayName: 'Comprehensions', difficultyBand: 'intermediate' },
  { id: 'loops', displayName: 'Loops', difficultyBand: 'basic' },
  { id: 'string_methods', displayName: 'String Methods', difficultyBand: 'basic' },
  { id: 'booleans_and_conditionals', displayName: 'Booleans and Conditionals', difficultyBand: 'basic' },
  { id: 'numbers_and_strings', displayName: 'Numbers and Strings', difficultyBand: 'basic' },
  { id: 'functions_basic', displayName: 'Functions', difficultyBand: 'basic' },
]

const DIFFICULTY_ORDER = {
  basic: 0,
  intermediate: 1,
  advanced: 2,
}

async function main() {
  const args = parseArgs(process.argv.slice(2))
  const records = await loadRecords(args.input)
  const sql = buildSeedSql(records)
  const outputPath = resolve(args.output)

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, sql, 'utf8')

  process.stdout.write(`Wrote ${records.length} MBPP exercises to ${outputPath}\n`)
}

function parseArgs(argv) {
  const args = {
    input: '',
    output: DEFAULT_OUTPUT,
  }

  for (let index = 0; index < argv.length; index += 1) {
    const value = argv[index]

    if (value === '--input') {
      args.input = argv[index + 1] ?? ''
      index += 1
      continue
    }

    if (value === '--output') {
      args.output = argv[index + 1] ?? DEFAULT_OUTPUT
      index += 1
      continue
    }
  }

  if (!args.input) {
    throw new Error('Usage: npm run import:mbpp -- --input <file-or-url> [--output <sql-file>]')
  }

  return args
}

async function loadRecords(input) {
  if (/^https?:\/\//i.test(input)) {
    const response = await fetch(input)

    if (!response.ok) {
      throw new Error(`Failed to fetch MBPP data: ${response.status} ${response.statusText}`)
    }

    return normalizeMbppShape(await response.text())
  }

  const content = await readFile(resolve(input), 'utf8')
  return normalizeMbppShape(content)
}

function normalizeMbppShape(content) {
  const trimmed = content.trim()

  if (!trimmed) {
    throw new Error('MBPP input is empty.')
  }

  if (trimmed.startsWith('[')) {
    const parsed = JSON.parse(trimmed)

    if (!Array.isArray(parsed)) {
      throw new Error('Expected MBPP JSON input to be an array.')
    }

    return parsed
  }

  return trimmed
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line, index) => {
      try {
        return JSON.parse(line)
      } catch (error) {
        throw new Error(
          `Failed to parse MBPP JSONL at line ${index + 1}: ${error instanceof Error ? error.message : String(error)}`,
        )
      }
    })
}

function buildSeedSql(records) {
  const createdAt = Date.now()
  const statements = [
    '-- Generated by scripts/import-mbpp.mjs',
    'BEGIN TRANSACTION;',
  ]

  for (const record of records) {
    const exercise = buildExercise(record)
    const hash = hashExercise(exercise)

    statements.push(
      [
        'INSERT OR IGNORE INTO exercises (',
        '  id,',
        '  prompt_md,',
        '  starter_code,',
        '  reference_solution,',
        '  tests,',
        '  difficulty_band,',
        '  hash,',
        '  created_at,',
        '  parent_exercise_id',
        ') VALUES (',
        `  ${sqlString(exercise.id)},`,
        `  ${sqlString(exercise.promptMd)},`,
        `  ${sqlString(exercise.starterCode)},`,
        `  ${sqlString(exercise.referenceSolution)},`,
        `  ${sqlString(exercise.tests)},`,
        `  ${sqlString(exercise.difficultyBand)},`,
        `  ${sqlString(`mbpp:${hash}`)},`,
        `  ${createdAt},`,
        '  NULL',
        ');',
      ].join('\n'),
    )

    for (const topic of exercise.topics) {
      statements.push(
        `INSERT OR IGNORE INTO exercise_topics (exercise_id, topic_id) VALUES (${sqlString(exercise.id)}, ${sqlString(topic.id)});`,
      )
    }
  }

  statements.push('COMMIT;')
  statements.push('')
  return statements.join('\n')
}

function buildExercise(record) {
  const prompt = asTrimmedString(record.prompt)
  const code = asTrimmedString(record.code)
  const testImports = Array.isArray(record.test_imports) ? record.test_imports.map(asTrimmedString) : []
  const testList = Array.isArray(record.test_list) ? record.test_list.map(asTrimmedString) : []

  if (!prompt || !code || !testList.length) {
    throw new Error(`MBPP record ${record.task_id ?? 'unknown'} is missing prompt/code/tests.`)
  }

  const definedNames = extractDefinedNames(code)
  const testedNames = extractTestedNames(testList, definedNames)
  const starterCode = buildStarterCode(code, testedNames)
  const promptMd = buildPromptMarkdown(record.task_id, prompt, testedNames[0] ?? null)
  const tests = buildTests(testImports, testList, testedNames)
  const topics = inferTopics(prompt, code, tests)
  const difficultyBand = topics.reduce(
    (highest, topic) =>
      DIFFICULTY_ORDER[topic.difficultyBand] > DIFFICULTY_ORDER[highest] ? topic.difficultyBand : highest,
    'basic',
  )

  return {
    id: `mbpp-${record.task_id}`,
    promptMd,
    starterCode,
    referenceSolution: ensureTrailingNewline(code),
    tests,
    difficultyBand,
    topics,
  }
}

function asTrimmedString(value) {
  return typeof value === 'string' ? value.trim() : ''
}

function extractDefinedNames(code) {
  const names = new Set()

  for (const match of code.matchAll(/^def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/gm)) {
    names.add(match[1])
  }

  for (const match of code.matchAll(/^class\s+([A-Za-z_][A-Za-z0-9_]*)\s*[(:]/gm)) {
    names.add(match[1])
  }

  return names
}

function extractTestedNames(testList, definedNames) {
  const names = new Set()

  for (const assertion of testList) {
    for (const match of assertion.matchAll(/([A-Za-z_][A-Za-z0-9_]*)\s*\(/g)) {
      if (definedNames.has(match[1])) {
        names.add(match[1])
      }
    }
  }

  if (!names.size) {
    for (const name of definedNames) {
      names.add(name)
      break
    }
  }

  return [...names]
}

function buildStarterCode(code, testedNames) {
  const importBlock = [...code.matchAll(/^(?:from\s+.+\s+import\s+.+|import\s+.+)$/gm)]
    .map((match) => match[0])
    .join('\n')
  const functionName = testedNames.find((name) => new RegExp(`^def\\s+${name}\\s*\\(`, 'm').test(code))
  const signatureMatch = functionName
    ? code.match(new RegExp(`^def\\s+${functionName}\\s*\\(([^)]*)\\)\\s*:`, 'm'))
    : code.match(/^def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*:/m)

  if (signatureMatch) {
    const name = functionName ?? signatureMatch[1]
    const params = functionName ? signatureMatch[1] : signatureMatch[2]
    const body = `def ${name}(${params}):\n    pass\n`
    return importBlock ? `${importBlock}\n\n${body}` : body
  }

  return importBlock ? `${importBlock}\n\n# Write your solution here\n` : '# Write your solution here\n'
}

function buildPromptMarkdown(taskId, prompt, functionName) {
  const lines = [
    `# MBPP ${taskId}`,
    '',
    prompt,
  ]

  if (functionName) {
    lines.push('', '## Function name', '', `Implement \`${functionName}\`.`)
  }

  return `${lines.join('\n').trim()}\n`
}

function buildTests(testImports, testList, testedNames) {
  const imports = [...testImports]

  if (testedNames.length) {
    imports.push(`from solution import ${testedNames.join(', ')}`)
  } else {
    imports.push('import solution')
  }

  const sections = [imports.join('\n')]

  for (let index = 0; index < testList.length; index += 1) {
    sections.push(`\n\ndef test_mbpp_case_${index + 1}():\n    ${testList[index]}`)
  }

  return `${sections.join('')}\n`
}

function inferTopics(prompt, code, tests) {
  const haystack = `${prompt}\n${code}\n${tests}`.toLowerCase()
  const matches = []

  const maybeAdd = (topicId, pattern) => {
    if (pattern.test(haystack)) {
      const topic = TOPIC_DEFINITIONS.find((entry) => entry.id === topicId)
      if (topic && !matches.some((entry) => entry.id === topic.id)) {
        matches.push(topic)
      }
    }
  }

  maybeAdd('regex_basic', /\bimport re\b|regex|regular expression|underscore/)
  maybeAdd('json', /\bimport json\b|\bjson\b/)
  maybeAdd('csv', /\bimport csv\b|\bcsv\b/)
  maybeAdd('datetime', /\bimport datetime\b|\bfrom datetime\b|\bdate\b|\btime\b/)
  maybeAdd('collections_module', /\bimport collections\b|\bfrom collections\b|counter|defaultdict|deque/)
  maybeAdd('itertools', /\bimport itertools\b|\bfrom itertools\b/)
  maybeAdd('functools', /\bimport functools\b|\bfrom functools\b/)
  maybeAdd('typing_basic', /\bimport typing\b|\bfrom typing\b|list\[|dict\[|tuple\[/)
  maybeAdd('classes_basic', /\bclass\s+[A-Za-z_]/)
  maybeAdd('dataclasses', /\bdataclass\b|\bfrom dataclasses\b/)
  maybeAdd('generators', /\byield\b|generator/)
  maybeAdd('exceptions', /\btry:\b|\bexcept\b|exception/)
  maybeAdd('sets', /\bset\(/)
  maybeAdd('dicts', /\bdict\b|\{.*:.*\}|key|value/)
  maybeAdd('tuples', /\btuple\b|test_tup|\btuples\b/)
  maybeAdd('lists', /\blist\b|\blists\b|\bappend\b/)
  maybeAdd('comprehensions', /\[[^\n]*for[^\n]*in[^\n]*\]|\{[^\n]*for[^\n]*in[^\n]*\}/)
  maybeAdd('loops', /\bfor\b|\bwhile\b/)
  maybeAdd('string_methods', /string|\bstrip\b|\bsplit\b|\bjoin\b|\blower\b|\bupper\b/)
  maybeAdd('booleans_and_conditionals', /\bif\b|\belif\b|\belse\b|\btrue\b|\bfalse\b/)
  maybeAdd('numbers_and_strings', /number|integer|float|string|digit|prime|sum|product|perimeter|volume/)

  if (!matches.length) {
    matches.push(TOPIC_DEFINITIONS.find((topic) => topic.id === 'functions_basic'))
  }

  if (!matches.some((topic) => topic.id === 'functions_basic')) {
    matches.unshift(TOPIC_DEFINITIONS.find((topic) => topic.id === 'functions_basic'))
  }

  return matches.filter(Boolean).slice(0, 2)
}

function ensureTrailingNewline(value) {
  return value.endsWith('\n') ? value : `${value}\n`
}

function hashExercise(exercise) {
  return createHash('sha256')
    .update(
      JSON.stringify({
        promptMd: exercise.promptMd,
        starterCode: exercise.starterCode,
        referenceSolution: exercise.referenceSolution,
        tests: exercise.tests,
      }),
    )
    .digest('hex')
}

function sqlString(value) {
  if (value === null) {
    return 'NULL'
  }

  return `'${String(value).replace(/'/g, "''")}'`
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
