INSERT OR IGNORE INTO topics (id, display_name, difficulty_band) VALUES
  ('variables', 'Variables', 'basic'),
  ('numbers_and_strings', 'Numbers and Strings', 'basic'),
  ('lists', 'Lists', 'basic'),
  ('tuples', 'Tuples', 'basic'),
  ('dicts', 'Dicts', 'basic'),
  ('sets', 'Sets', 'basic'),
  ('booleans_and_conditionals', 'Booleans and Conditionals', 'basic'),
  ('loops', 'Loops', 'basic'),
  ('functions_basic', 'Functions', 'basic'),
  ('string_methods', 'String Methods', 'basic'),
  ('formatting_fstrings', 'Formatting and f-strings', 'basic'),
  ('input_output_print', 'Input and Output', 'basic'),
  ('comprehensions', 'Comprehensions', 'intermediate'),
  ('pathlib', 'Pathlib', 'intermediate'),
  ('file_io', 'File I/O', 'intermediate'),
  ('exceptions', 'Exceptions', 'intermediate'),
  ('classes_basic', 'Classes', 'intermediate'),
  ('dataclasses', 'Dataclasses', 'intermediate'),
  ('iterators', 'Iterators', 'intermediate'),
  ('generators', 'Generators', 'intermediate'),
  ('decorators_basic', 'Decorators', 'intermediate'),
  ('context_managers', 'Context Managers', 'intermediate'),
  ('typing_basic', 'Typing', 'intermediate'),
  ('regex_basic', 'Regular Expressions', 'intermediate'),
  ('json', 'JSON', 'intermediate'),
  ('csv', 'CSV', 'intermediate'),
  ('cli_argparse', 'argparse', 'intermediate'),
  ('datetime', 'Datetime', 'intermediate'),
  ('collections_module', 'collections', 'intermediate'),
  ('decorators_advanced', 'Advanced Decorators', 'advanced'),
  ('generators_advanced', 'Advanced Generators', 'advanced'),
  ('typing_advanced', 'Advanced Typing', 'advanced'),
  ('metaclasses', 'Metaclasses', 'advanced'),
  ('async_basic', 'Async', 'advanced'),
  ('functools', 'functools', 'advanced'),
  ('itertools', 'itertools', 'advanced'),
  ('pattern_matching', 'Pattern Matching', 'advanced'),
  ('protocols_abstractbase', 'Protocols and ABCs', 'advanced');
